apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redhat-packages-credentials
  namespace: sdlc-control-plane
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secret-store
    kind: ClusterSecretStore
  target:
    name: redhat-packages-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: sdlc/lightwell-network
        property: username
    - secretKey: password
      remoteRef:
        key: sdlc/lightwell-network
        property: password
